#!/bin/bash
#PBS -P MEG
#PBS -N unzip_MEG
#PBS -o /project/MEG/unzip_MEG.out
#PBS -j oe
#PBS -l select=1:ncpus=2:mem=20GB
#PBS -l walltime=72:00:00

# Navigate to Cogitate MEG dir
mkdir -p /project/MEG/data/Cogitate_MEG
cd /project/MEG/data/Cogitate_MEG
# Download batch 1 + 2 zip
wget https://cogitate-bundles.ae.mpg.de/20231231_cog_exp1_bids_meeg_batch1_34c48f7a-6302-480e-858c-99f161b1e86c.zip & wget https://cogitate-bundles.ae.mpg.de/20231231_cog_exp1_bids_meeg_batch2_787edd9d-6440-47df-ba87-ed6b52a3b803.zip
# wget https://cogitate-bundles.ae.mpg.de/20231231_cog_exp1_bids_meeg_batch2_787edd9d-6440-47df-ba87-ed6b52a3b803.zip

# Unzip the files when those commands are done
wait

for subject in CA158 CA167 CB031 CB045 CB084; do 
    unzip 20231231_cog_exp1_bids_meeg_batch2_787edd9d-6440-47df-ba87-ed6b52a3b803.zip "mnt/beegfs/workspace/2023-0385-Cogitatedatarelease/CURATE/COG_MEEG_EXP1_BIDS_BATCH2/sub-${subject}/*" -d "/project/hctsa/annie/data/Cogitate_MEG/" 
    unzip 20231231_cog_exp1_bids_meeg_batch1_34c48f7a-6302-480e-858c-99f161b1e86c.zip "mnt/beegfs/workspace/2023-0385-Cogitatedatarelease/CURATE/COG_MEEG_EXP1_BIDS_BATCH1/sub-${subject}/*" -d "/project/hctsa/annie/data/Cogitate_MEG/" 
done
# unzip "20231231_cog_exp1_bids_meeg_batch1_34c48f7a-6302-480e-858c-99f161b1e86c.zip" & unzip "20231231_cog_exp1_bids_meeg_batch2_787edd9d-6440-47df-ba87-ed6b52a3b803.zip"

# Move batch1 to hctsa project and unzip there
#mv "20231231_cog_exp1_bids_meeg_batch1_34c48f7a-6302-480e-858c-99f161b1e86c.zip" /project/hctsa/annie/data/Cogitate_MEG/
#cd /project/hctsa/annie/data/Cogitate_MEG/
#unzip "20231231_cog_exp1_bids_meeg_batch1_34c48f7a-6302-480e-858c-99f161b1e86c.zip"
