#!/bin/bash
#PBS -j oe
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=1:mem=20GB:mpiprocs=1
#PBS -V
#PBS -P hctsa


### project to Artemis ###
mv -v /project/hctsa/annie/data/Cogitate_MEG/derivatives/MEG_time_series/* /project/MEG/data/Cogitate_MEG/derivatives/MEG_time_series/

for file in $(find . -name "sub-C*.zip"); do
    file_base=$(echo $file | sed 's/.\///')
    cp -v $file_base /rds/PRJ-MEG/Cogitate_MEG/derivatives/preprocessing/ &
done
wait
echo "Done copying all data"

rm -rv sub-CA1*.zip

##### RDS to project ###
for subject in $(find /rds/PRJ-MEG/Cogitate_MEG/derivatives/preprocessing/ -maxdepth 1 -mindepth 1 -type d -name "sub-CB*"); do
    subject_base=$(basename $subject)
    echo "Copying preprocessed data for: $subject_base"
    cp -rv /rds/PRJ-MEG/Cogitate_MEG/derivatives/preprocessing/$subject_base . &
done
wait
echo "Done copying all data"

rm -rv /rds/PRJ-MEG/Cogitate_MEG/derivatives/preprocessing/sub-CA14*