#!/bin/bash
#PBS -j oe
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=10:mem=20GB
#PBS -o /project/MEG/data/Cogitate_MEG/zip_proc.out
#PBS -V
#PBS -P hctsa

cd /project/MEG/data/Cogitate_MEG/derivatives/preprocessing
# cd /project/hctsa/annie/data/Cogitate_MEG/derivatives/preprocessing

for subject in $(find . -maxdepth 1 -type d -name "sub-14*" | cut -d "/" -f 2); do
    echo "Zipping data for: $subject"
    rm -rv $subject/ses-1/meg/figures
    ( zip -r ${subject}_preproc.zip ${subject}/* ) &
done
wait